---
apiVersion: v1
kind: Service
metadata:
  name: mysite
spec:
  type: LoadBalancer
  selector:
    app: mysite
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite
  labels:
    app: mysite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysite
  template:
    metadata:
      labels:
        app: mysite
    spec:
      containers:
      - name: mysite
        image: europe-west3-docker.pkg.dev/GOOGLE_PROJECT/mysite-repo/mysite:latest