name: Build and Push React Image to Google Cloud Platform
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Code Checkout
      - name: Code Checkout
        uses: actions/checkout@v3

      # Set up Cloud SDK
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          install_components: 'gke-gcloud-auth-plugin' # Deployment
          export_default_credentials: true

      # Push Docker to Artifact Registry
      - name: Build and Push Docker Image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth list --filter=status:ACTIVE --format="value(account)"
          gcloud auth configure-docker europe-west3-docker.pkg.dev
          docker build -t europe-west3-docker.pkg.dev/${{secrets.GOOGLE_PROJECT}}/mysite-repo/mysite:latest .
          docker push europe-west3-docker.pkg.dev/${{secrets.GOOGLE_PROJECT}}/mysite-repo/mysite:latest
      
      # Deploy to Google Cloud Run
      - name: Deployt to Google Cloud Run
        id: 'deploy'
        run: |
          gcloud auth list --filter=status:ACTIVE --format="value(account)"
          gcloud run deploy ${{ secrets.GOOGLE_SERVICE }} --image \
          europe-west3-docker.pkg.dev/${{secrets.GOOGLE_PROJECT}}/mysite-repo/mysite:latest \
          --platform managed --region europe-west3 --allow-unauthenticated

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'