name: Deployment
on:
  push:
    branches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run docker-compose
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"
          up-flags: "--build"
          down-flags: "--volumes"
        env:
          CUSTOM_VARIABLE: "test"
  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist
      - name: Output Contents
        run: ls
      - name: Deploy to Google Cloud Storage
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          project_id: mysite-bucket-1

      - name: Deploy via GCS
        run: |
          gsutil -m rm -rf gs://mysite-bucket-1/* || echo "$?"
          gsutil -m cp -r ./dist gs://mysite-bucket-1