name: Deployment
on:
  push:
    branches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
      - name: Install Dependencies
        run: npm install
      - name: Build Project
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: dist
  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist
      - name: Output Contents
        run: ls
      - name: Deploy to Google Cloud Storage
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          project_id: mysite-bucket-1

      - name: Deploy via GCS
        run: |
          gsutil -m rm -rf gs://mysite-bucket-1/* || echo "$?"
          gsutil -m cp -r ./dist gs://mysite-bucket-1